name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'

    - name: Start MongoDB with mongo-action
      uses: DigiPie/mongo-action@v2.0.1
      with:
        image_version: "latest"  # Optional, default is 'latest'
        port: "27017"  # Optional, default is 27017

    - name: Install dependencies
      run: npm install
      working-directory: ./backend

    - name: Run tests
      run: npm test
      working-directory: ./backend
